language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install fur -g
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "ZNJDuTS12joQSq33RpDawe/RZkc1thPeUjTeYxk/pAXYsbFoIjXiqZ9Mji4+9rc07bb7NbxXgW/oyfx0rjmEPZZKJWhc0AVN4nvBaaUYyZfFw4cbayGVE3yVsJWYmuGdzC4qClho2tAjmy/lGkrkzDwYbNVVZF5vb0tsyDjT+9b032U0Fz8x1D/NDX45MdtJ5K2P3daL4C+EDOjovnY3G1zGxT3+9YMr711wmVkwzsCmyDUnwxPTqGy9HiznE8SvWXkfCzw4SWJQfQaRCV81UFqvOLBWBRVRNyWgpEOZ1m/hwU/0tvkt5PPOAvNorEAMGc1AqWVntXhSABF+tREJpTpctG+0+L5xTa+M96y1cGSkRgSKKJJcsTtfuL2YFrD8zPq1NMr0epNPhse7bccr0h3ahhqhhsLAT6fZl3y+X38He9i4AZkOSdhOJJg/R12QIb/A4KiYwVVbjbdXgjZQFpVHmYfasXj3txwPRl1rGDVF3IJCX+adFdq1xEtur+1GPeA0wT1uWwkf67oHL3J1pTV37WL/VphEHhC7yt/jXoBqK08TzQunvbZkFHDqNAXg1f2s5FAF211+8UH7HQa/pnlWYu8LUX9m3+yBj9PFoUVQYY+rMq/fLFbfvxdloccw46qE9zu+qVwtvFPnGnyS/rvNEDDlCtu+6itg6yReJKk="