language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install fur -g
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  global:
    secure: DS/VTVX/p/7ySWoGhq689L4qOGWbZd39ehQYEeYEr8EMH1NuTkU+aBJ5RJ09fHSQ0ijzZcOfXqceKEV9LotHx9EtBBxMmctJPc0yvmL3UD+Wsnh0g5rXZqwDi0NZaXMnFZt+YxZ/u/eB4K/CcK4u8zV3eN2pHrpKGN/DAZ1Dzee7jVsmRH9CZXElNFB1sBB0m3WT/rO1XeMARtqCKFKr+O22kbupG0ZiG7CNttoAp5CWzyejjEg/Vbs4zwjZGBNQvz8qRn8gz32i8FSvdQYF6e8Ved16ELRWfHE8pJbHbXkGrR4euFm7huexvqZeR/f6CJijsG2skwkvuW5DOF+FcZ5wZ7IGTYEiTLA2zWLnrHZJRt2a6wBy1Y8tW2QGaMmnL8LZ71CAQOEdpVCs9k67EKA8BeXHkrjuIwM4luoIdk0BE/uslIUIhUfwM/rkriBS23/YdYrGHPS29BbQQLzKxgfwblVMdGue1RKB7GHAFmboUIcXgdXkg5zzxU1ex/tUnlWc6y/gJ2PnsxwhN5cZblDI+YmS4SzZgWffeHqveypMmAvcsBIaJ8hwn85V7BlOHwvu08U9KTqJUhv8hB9kOVF/Vga8Wfm952oTKdHcteaWEMPACXHTuEth5VgoxGP+78/T2HZx16xthQ2xTIQZwz5gM5C9MD+djFaqV2/5dV0=
