language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install fur -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "XlSDYF7xA5KoWyD1OIMxVI5jsAnWg8qU4qf8F14kSMVaSCpJMvI9sfEZlSm/G3pe8FcXWFszk+kGVFz7ZpK384b0wA/GEuniyA8QOx3IrMeXgJtIbVug6o14Z64/zASSmyr7l8l/2JQJoQYOtkgqdNmiQfhd5p+/m9uaXm9FwnMTyN8cnhr1mR3bq9kzaHRhlKK5ItfruxI1NvNjIUyXYH5ggXjxgWN0boXA5cvQPvGjhZHUN/4d9xIu9/ZYiRu7DJPCj4Pdn+M/VLCaY7slhmZzW60q09sQzMyUR+iXOfQ4JY4NypRmu3RcJJpPP+KXFazhlcq6gPDNNPTSPbTAZJPZgN+fh//jQqyjNQjH/Al7PUjSxrL56vBMh/0klrdKr5LjFldifAvLeI5oiGGky/IsCenK+iDk7jl4G2+ad60tQZCT+04J0xWOXMUv2zdIMzpgmCJBWJqkKcTVV10ymUUlMxLUJ1UHnaxIWas2j8d/XsX2iS3vROThq1e3Ck5PlAvT3hR2zE/c8bSHCJNOrBzAt8u8lptRy9RUkEDh22romLa+kcfagHK8hWbx6Uko51zYO/gu5ADz+uio8j8FB0rBPme6t87qjXhOPqu4qSdUxT0G64TNlMbaGJ4eqTy1B+i68Bp7LRSezFJYIxbzq2Pc4/NDWJ9ZTxyBzu6nwNw="