language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install fur -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "VLrUiqbgmiWvI1zGaqPH1WH5ibwIYezuJ7AeeZ2vTtoWtVYt3YCUVKQd9sVIMF3+nqJU/YDxbKrXuV3egDsf1LjWRa1IwA+VkxMTvHBVp/Z8sghZylzQdinT+Xnt3yJOUbmfbXg5A1e5sEmvaWeuycrjKfr9Mx2Vj/VSAZ8MS6wjAPf0ztsMqfT4BCbS/WgM5vbO03/uvslnDDKYTLn1Td5VxoxVL26iUoQny6QZjQOiJ6jY55bcPh7qO6/7/DN/zIaFeIlAm2EIn+TuG5RcijZ6J6AoECDnbK2BRZ0dI0u2L3C5KH/vKc3OUEao/DjR7NJZhX/cJzN/ScITOK+Qqf+mp2MGuDPmtEIyQKheAf/fTYC1Mw/GKQnikPQbVHnW/xm2DIVB35vxsyKmWzQg7263Dn/vIRRKW/uzXElCGBKO+5NbaxAhC7LCdmkLNs+PrHDvgPd4sN0hShYvhlZBO15w0ucHUeiTAC0k2UsWeEHZ5EH70j3e9Y/KLUTlEoLQGy3VCZlXQ2mcXquu6gMXoj+osygmPd74CjjG9NgGiZkyvCL2CI2yDgMA/ZYBCm1IdQKcmpczFYi2sOR5Ds1JNlg5SiHK57HNT+yylMHYNvb6vUUYeIaLx/1c37YkG+WsGeEAjFy1qnjIDMY9WtQCmEhAiig5v5EvadwXYcQFGz4="
